---
title: "InDen Project | B cells | Isolate Plasmablasts"
author: "Giorgio Gonnella"
date: 2024-08-16
output:
  html_document:
    theme: sandstone
params:
  pfx: "/srv/baia/"
  libpath: "/home/giorgio/R-pkg-Seurat5/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F, warning=F, echo=T)
.libPaths(c(params$libpath, .libPaths()))

library(Seurat)
library(harmony)
library(scProportionTest)

prj_root <- paste0(params$pfx, "inden/")
analysis_root <- paste0(prj_root, "analysis-1/")

prev_step_dir <- paste0(analysis_root, "steps/105.0.P.B.split_plasmablasts/")
input_var_dir <- paste0(prev_step_dir, "results/vars/")
if (!dir.exists(input_var_dir)) {
  stop("Input variable directory does not exist: ", input_var_dir)
}

this_step_dir <- paste0(analysis_root, "steps/109.0.P.B.isolate_plasmablasts/")
if (!dir.exists(this_step_dir)) {
  stop("Current step directory does not exist: ", this_step_dir)
}

var_dir <- paste0(this_step_dir, "results/vars/")
dir.create(var_dir, recursive = T)

helpers_dir = paste0(prj_root, "helpers/")
source(paste0(helpers_dir, "de_helpers.R"))
```

```{r load_data, include = FALSE}
so <- readRDS(file = paste0(input_var_dir, "splitted_so.rds"))
```

# Isolate the cells

```{r isolate_emcd8}
Idents(so) <- so$pruned.labels_singleR_fine
Pb <- subset(so, idents=c("Plasmablasts"))
```

# Integration

```{r integration}
Pb <- RunHarmony(object = Pb, reduction.use = "pca",
                 group.by.vars = "orig.ident")
```

# UMAP

```{r umap}
myDims <- 1:40
Pb <- RunUMAP(object = Pb, dims = myDims,
              reduction = "harmony", reduction.name = "umapharm")
```

# Clustering

```{r clustering}
reS <- c(0.2)
Pb <- FindNeighbors(Pb, dims = myDims, reduction = "harmony",
                    graph.name = "harmsnn")
Pb <- FindClusters(Pb, resolution = reS, graph.name = "harmsnn")
```

```{r select_resolution}
Pb@misc$sel_res <- 0.2
Pb@misc$sel_res_col <- paste0("harmsnn_res.", Pb@misc$sel_res)
```

# Cell type proportions test

```{r ct_prop_test}
prop_test <- sc_utils(Pb)
Pb@misc$prop_test <- permutation_test(
        prop_test, cluster_identity = Pb@misc$sel_res_col,
        sample_1 = "Subclinical", sample_2 = "Hospitalized",
        sample_identity = "clinical_condition"
    )
```

# Differential expression analysis

```{r}
selgenes <- select_genes(so, 100)
```

```{r}
pseudo <- AggregateExpression(Pb,
                              assays = "RNA",
                              return.seurat = TRUE,
                              group.by = c("clinical_condition", "sample",
                                           "harmsnn_res.0.2"))
pseudo$ident.cond <- paste0(pseudo$harmsnn_res.0.2,
                               "_", pseudo$clinical_condition)
Idents(pseudo) <- "ident.cond"

Pb@misc$em_de <- list()
Pb@misc$em_de$all <- list()
Pb@misc$em_de$pval_filt <- list()

for (cl in unique(pseudo$harmsnn_res.0.2)) {
    ident.1 <- paste0(cl, "_" , "Subclinical")
    ident.2 <- paste0(cl, "_" , "Hospitalized")
    all <- FindMarkers(pseudo, features = selgenes,
                ident.1 = ident.1, ident.2 = ident.2, test.use = "DESeq2",
                min.cells.group = 0)
    Pb@misc$em_de$all[[cl]] <- all
    pval_filt <- all[all$p_val_adj < 0.05, ]
    pval_filt <- na.omit(pval_filt)
    Pb@misc$em_de$pval_filt[[cl]] <- pval_filt
}
```

## Saving data

```{r, echo=TRUE}
saveRDS(Pb, file = paste0(var_dir, "isolated_blasmablasts.rds"))
```
# Session info

```{r}
sessionInfo()
```
