---
title: "InDen | T cells | Pseudobulk DE Seurat 5 | Cell types"
author: "Giorgio Gonnella"
date: 2024-06-13
output:
  html_document:
    theme: sandstone
params:
  pfx: "/srv/baia/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, comment = FALSE, echo = TRUE)

library(Seurat)
library(dplyr)

prj_root <- paste0(params$pfx, "inden/")
analysis_root <- paste0(prj_root, "analysis-1/")

prev_step_dir <- paste0(analysis_root, "steps/108.0.P.B.split_plasmablasts/")
input_var_dir <- paste0(prev_step_dir, "results/vars/")

this_step_dir <- paste0(analysis_root, "steps/109.0.P.B.de_split_plasmablasts/")
results_dir <- paste0(this_step_dir, "results/celltypes_s5/")
dir.create(results_dir, recursive = TRUE)
```

```{r load_input_data}
so <- readRDS(file = paste0(input_var_dir, "splitted_so.rds"))
```

```{r select_cluster_identity}
clusters_col <- "pruned.labels_singleR_fine.mod"
```


```{r select_genes}
selgenes <- rownames(so)
print(paste0("Initial number of genes: ", length(selgenes)))

rs <- Matrix::rowSums(so@assays$RNA@counts)
print(summary(rs))
#library(vioplot)
#vioplot::vioplot(rs, main = "Violin plot of row sums")
minrowsum = 0
print(paste0("Minimum row sum parameter: ", minrowsum))
selgenes <- rownames(so)[rs >= minrowsum]
print(paste0("Number of selected genes passing rowsum filter: ", length(selgenes)))

TCRgenes <- grep(pattern = "^TR[ABGD][VC]", selgenes, value = TRUE)
print(paste0("Number of TCR genes to filter out: ", length(TCRgenes)))
Ig_genes <- c(grep(pattern = "^IG[HLK][VDJ]", selgenes, value = TRUE),
               c("IGHG1", "IGHD", "IGHE", "IGHA[12]", "IGHG[1234]", "IGKC", "IGLC[1234567]", "AC233755.1"))
print(paste0("Number of IG genes to filter out: ", length(Ig_genes)))
MTgenes <- grep(pattern = "^MT-", selgenes, value = TRUE)
print(paste0("Number of Mitochondrial genes to filter out: ", length(MTgenes)))
RiboGenes <- grep(pattern = "^RP[LS]", selgenes, value = TRUE)
print(paste0("Number of Ribosomal genes to filter out: ", length(RiboGenes)))
MoreGenesToFilter <- c("MALAT1")
print(paste0("Further genes to filter out: ", MoreGenesToFilter))
GenesToFilter = c(TCRgenes, Ig_genes, MTgenes, RiboGenes, MoreGenesToFilter)
print(paste0("Total number of genes to filter out: ", length(GenesToFilter)))

selgenes <- selgenes[!selgenes %in% GenesToFilter]
print(paste0("Final number of selected genes: ", length(selgenes)))
```


```{r}
all.de <- list()
pval_filt.de <- list()
n_pval_filt.de <- list()
pval_lfc_filt.de <- list()
n_pval_lfc_filt.de <- list()
#tests_to_try = c("DENV_Serotype", "gender", "DayCat", "clinical_condition")
tests_to_try = c("clinical_condition")
clusters_col <- "pruned.labels_singleR_fine.mod"

for (test_name in tests_to_try) {
    so_new<-so
    split_col = test_name
    group_by = c(split_col, "sample", clusters_col)
    pseudo <- AggregateExpression(so_new, assays = "RNA",
                                  return.seurat = TRUE, group.by = group_by)
    rm(so_new)
    clusters_data <- pseudo@meta.data[[clusters_col]]
    pseudo$split.clusters <- paste0(pseudo@meta.data[[split_col]], "_", clusters_data)
    split_levels <- unique(pseudo@meta.data[[split_col]])
    Idents(pseudo) <- "split.clusters"
    cluster_names <- unique(clusters_data)
    freqs = table(Idents(pseudo))
    for (cluster in cluster_names) {
      ident.1 <- paste0(split_levels[1], "_", cluster)
      ident.2 <- paste0(split_levels[2], "_", cluster)
      if ((ident.1 %in% Idents(pseudo)) && (ident.2 %in% Idents(pseudo))
          && (freqs[[ident.1]] >= 3) && (freqs[[ident.2]] >= 3)) {
        print(paste0("Computing DESeq2 for ", test_name, " ", ident.1, " vs ", ident.2, "..."))
        markers <- FindMarkers(pseudo, features = selgenes, logfc.threshold = 0.1,
                    ident.1 = ident.1, ident.2 = ident.2, test.use = "DESeq2")
        if (!is.null(markers)) {
          all.de[[cluster]][[test_name]] <- markers
          pvf <- markers %>% filter(p_val_adj < 0.05)
          sz <- nrow(pvf)
          pval_filt.de[[cluster]][[test_name]] <- pvf
          n_pval_filt.de[[cluster]][[test_name]] <- sz
          print(paste0("  Number of genes with adj p-value < 0.05: ", sz))
          plvf <- pvf %>% filter(avg_log2FC >= 0.58 | avg_log2FC <= -0.58)
          sz <- nrow(plvf)
          pval_lfc_filt.de[[cluster]][[test_name]] <- plvf
          n_pval_lfc_filt.de[[cluster]][[test_name]] <- sz
          print(paste0("    and abs(log2FC) >= 0.58: ", sz))
          rm(pvf)
          rm(plvf)
          rm(sz)
        }
        rm(markers)
      }
    }
}

# Compute it also for the unsplitted Plasmablasts

clusters_col2 <- "pruned.labels_singleR_fine"
for (test_name in tests_to_try) {
    so_new<-so
    split_col = test_name
    group_by = c(split_col, "sample", clusters_col2)
    pseudo2 <- AggregateExpression(so_new, assays = "RNA",
                                  return.seurat = TRUE, group.by = group_by)
    rm(so_new)
    clusters_data2 <- pseudo2@meta.data[[clusters_col2]]
    pseudo2$split.clusters <- paste0(pseudo2@meta.data[[split_col]], "_", clusters_data2)
    split_levels <- unique(pseudo2@meta.data[[split_col]])
    Idents(pseudo2) <- "split.clusters"
    cluster_names2 <- c("Plasmablasts")
    freqs2 = table(Idents(pseudo2))
    for (cluster in cluster_names2) {
      ident.1 <- paste0(split_levels[1], "_", cluster)
      ident.2 <- paste0(split_levels[2], "_", cluster)
      if ((ident.1 %in% Idents(pseudo2)) && (ident.2 %in% Idents(pseudo2))
          && (freqs2[[ident.1]] >= 3) && (freqs2[[ident.2]] >= 3)) {
        print(paste0("Computing DESeq2 for ", test_name, " ", ident.1, " vs ", ident.2, "..."))
        markers <- FindMarkers(pseudo2, features = selgenes, logfc.threshold = 0.1,
                    ident.1 = ident.1, ident.2 = ident.2, test.use = "DESeq2")
        if (!is.null(markers)) {
          all.de[[cluster]][[test_name]] <- markers
          pvf <- markers %>% filter(p_val_adj < 0.05)
          sz <- nrow(pvf)
          pval_filt.de[[cluster]][[test_name]] <- pvf
          n_pval_filt.de[[cluster]][[test_name]] <- sz
          print(paste0("  Number of genes with adj p-value < 0.05: ", sz))
          plvf <- pvf %>% filter(avg_log2FC >= 0.58 | avg_log2FC <= -0.58)
          sz <- nrow(plvf)
          pval_lfc_filt.de[[cluster]][[test_name]] <- plvf
          n_pval_lfc_filt.de[[cluster]][[test_name]] <- sz
          print(paste0("    and abs(log2FC) >= 0.58: ", sz))
          rm(pvf)
          rm(plvf)
          rm(sz)
        }
        rm(markers)
      }
    }
}
```

```{r save_results}
fname <- paste0(results_dir, "pval_filt.de.tsv")
cat("cluster\tgene\tperc.1\tperc.2\tp_val\tp_val_adj\tlog2fc\n", file = fname)
for (cluster in c(cluster_names, "Plasmablasts")) {
  for (test_name in tests_to_try) {
    for (gene in rownames(pval_filt.de[[cluster]][[test_name]])) {
        cat(cluster, "\t", gene, "\t",
            pval_filt.de[[cluster]][[test_name]][gene, ]$pct.1, "\t",
            pval_filt.de[[cluster]][[test_name]][gene, ]$pct.2, "\t",
            pval_filt.de[[cluster]][[test_name]][gene, ]$p_val, "\t",
            pval_filt.de[[cluster]][[test_name]][gene, ]$p_val_adj, "\t",
            pval_filt.de[[cluster]][[test_name]][gene, ]$avg_log2FC, "\n",
            file = fname, append = TRUE)
    }
    cluster_name_sanitized = gsub(" ", "_", cluster)
    cluster_name_sanitized = gsub("/", "_", cluster_name_sanitized)
    fname_all <- paste0(results_dir, "all_genes.", cluster_name_sanitized,
                        ".", test_name, ".de.tsv")
    data <- all.de[[cluster]][[test_name]]
    data$gene <- rownames(data)
    data <- data[, c(ncol(data), 1:(ncol(data) - 1))]
    write.table(data,, file = fname_all, sep = "\t", quote = F, row.names = F)
  }
}
```

# Session info

```{r}
sessionInfo()
```

