---
title: "InDen B cells | Output barcodes table for Enclone analysis"
author: "Giorgio Gonnella"
date: "2024-11-21"
output:
  html_document:
    theme: sandstone
params:
  pfx: "/srv/baia/"
  libpath: "/home/giorgio/R-pkg-Seurat5/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F, warning=F, echo=T)
.libPaths(c(params$libpath, .libPaths()))

library(Platypus)

prj_root <- paste0(params$pfx, "inden/")
analysis_root <- paste0(prj_root, "analysis-1/")

input_step_dir <- paste0(analysis_root, "steps/110.0.P.B.BCR_analysis.platypus/")
input_var_dir <- paste0(input_step_dir, "results/vars/")
if (!dir.exists(input_var_dir)) {
  stop("Input variable directory does not exist: ", input_var_dir)
}

this_step_dir <- paste0(analysis_root, "steps/114.0.P.B.enclone_preparation/")
if (!dir.exists(this_step_dir)) {
  stop("Current step directory does not exist: ", this_step_dir)
}
metadata_dir <- paste0(this_step_dir, "metadata/")
if (!dir.exists(metadata_dir)) {
  stop("Metadata directory does not exist: ", metadata_dir)
}
metadata_file <- paste0(metadata_dir, "config.tsv")
if (!file.exists(metadata_file)) {
  stop("Metadata file does not exist: ", metadata_file)
}
tables_dir <- paste0(this_step_dir, "results/tables/")
dir.create(tables_dir, showWarnings = FALSE, recursive = TRUE)
json_dir <- paste0(this_step_dir, "results/json/")
dir.create(json_dir, showWarnings = FALSE, recursive = TRUE)
```

## Load data

```{r load_vgm}
vgm <- readRDS(file = paste0(input_var_dir, "vgm.rds"))
```

## Create barcode tabular file

Output barcodes table to TSV file for Enclone analysis
(sample, clinical condition, barcode, celltype, clonotype id,
clonotype frequency)

```{r create_tsv}
barcode_tab <- data.frame(
  sample = vgm$VDJ$sample,
  barcode = paste0(vgm$VDJ$orig_barcode, "-1"),
  celltype = vgm$VDJ$celltype,
  condition = as.character(vgm$VDJ$clinical_condition),
  clonotype_id = vgm$VDJ$clonotype_id,
  clonotype_size = vgm$VDJ$clonotype_size
)

write.table(barcode_tab, paste0(tables_dir, "vgm.tsv"),
            sep = "\t", quote = F, row.names = F)
```

```{r}
system(paste0("python3 ",
              this_step_dir, "scripts/filter_vgm_data.py ",
              tables_dir, "vgm.tsv ",
              metadata_file, " ",
              "--verbose ",
              "> ", json_dir, "all_contig_annotations.json"))
```

# Session info

```{r}
sessionInfo()
```
