---
title: "InDen Project | B cells | Analyse Isolated Plasmablasts"
author: "Giorgio Gonnella"
date: 2024-08-16
output:
  html_document:
    theme: sandstone
params:
  pfx: "/srv/baia/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, comment = FALSE, echo = TRUE)

# required libraries
library(Seurat)
library(viridis)
library(ggplot2)
library(ggrepel)
library(ggExtra)
library(gplots)
library(RColorBrewer)
library(reshape2)
library(ggsci)
library(dplyr)
library(harmony)
library(clusterProfiler)
library(scProportionTest)

prj_root <- paste0(params$pfx, "inden/")
analysis_root <- paste0(prj_root, "analysis-1/")

input_step_dir <- paste0(analysis_root, "steps/110.0.P.B.isolate_plasmablasts/")
input_var_dir <- paste0(input_step_dir, "results/vars/")

this_step_dir <- paste0(analysis_root, "steps/110.0.V.B.analysis.isolated_plasmablasts/")
plots_dir <- paste0(this_step_dir, "results/plots/")
dir.create(plots_dir, recursive = TRUE)
tables_dir <- paste0(this_step_dir, "results/tables/")
dir.create(tables_dir, recursive = TRUE)

```

```{r load_data, include = FALSE}
so <- readRDS(file = paste0(input_var_dir, "isolated_blasmablasts.rds"))
```

# UMAP plot

```{r umap_plot, fig.width=10, fig.height=6}
plt <- DimPlot(object = so, reduction = "umapharm", pt.size = 0.3,
        group.by = so@misc$sel_res_col, split.by="clinical_condition",
        cols = so@misc$cluster_cols)
fname <- paste0(plots_dir, "Pb.umap_plot_by_subcluster.svg")
ggsave(filename = fname, plot = plt, device = "svg")
plt
```

# Phase

```{r umap_plot_by_phase}
DimPlot(object = so, reduction = "umapharm", pt.size = 0.3,
        group.by = "Phase", split.by="clinical_condition",
        cols = so@misc$phase_cols)
```

# Cell type

```{r umap_plot_by_ct, fig.width=10, fig.height=6} 
plt <- DimPlot(object = so, reduction = "umapharm", pt.size = 0.3,
        group.by = "pruned.labels_singleR_fine.mod",
        split.by = "clinical_condition",
        cols = so@misc$fctype_mod_cols) +
  theme(legend.position = "bottom")
fname <- paste0(plots_dir, "Pb.umap_plot_by_celltype.svg")
ggsave(filename = fname, plot = plt, device = "svg")
plt
```

# Sample

```{r umap_plot_by_sample}
DimPlot(object = so, reduction = "umapharm", pt.size = 0.3,
        group.by = "sample", split.by="clinical_condition",
        cols = so@misc$sample_cols)
```

# Feature plots

```{r feature_plot_OASL}
FeaturePlot(so, features = "OASL",reduction = "umapharm",
            split.by="clinical_condition")
```

```{r feature_plot_HSPA8}
FeaturePlot(so, features = "HSPA8",reduction = "umapharm",
            split.by="clinical_condition")
```

```{r feature_plot_CCNB1}
FeaturePlot(so, features = "CCNB1",reduction = "umapharm",
            split.by="clinical_condition")
```

```{r feature_plot_MKI67}
FeaturePlot(so, features = "MKI67",reduction = "umapharm",
            split.by="clinical_condition")
```

# Cell types proportions

```{r}
prop_test <- sc_utils(so)
prop_test <- permutation_test(
        prop_test, cluster_identity = so@misc$sel_res_col,
        sample_1 = "Inapparent", sample_2 = "Hospitalized",
        sample_identity = "clinical_condition"
    )
```

```{r, fig.width=6, fig.height=3}
plt <- permutation_plot(prop_test)
fname <- paste0(plots_dir, "Pb.celltype_proportions.svg")
ggsave(filename = fname, plot = plt, device = "svg")
plt
```

```{r}
params.minrowsum = 100
rs <- Matrix::rowSums(so@assays$RNA@counts)
selgenes <- rownames(so)[rs>params.minrowsum]
TCRgenes <- grep(pattern = "^TR[AB][VC]", selgenes, value = TRUE)
Ig_genes <- c(grep(pattern = "^IG[HLK][VDJ]", selgenes, value = TRUE),
               c("IGHG1", "IGHD", "IGHE", "IGHA[12]", "IGHG[1234]",
                 "IGKC", "IGLC[1234567]", "AC233755.1"))
MTgenes <- grep(pattern = "^MT-", selgenes, value = TRUE)
RiboGenes <- grep(pattern = "^RP[LS]", selgenes, value = TRUE)
selgenes <- selgenes[!selgenes %in% c(TCRgenes, Ig_genes, MTgenes, RiboGenes)]
selgenes <- selgenes[-which(selgenes=="MALAT1")]
```

```{r}
pb_pseudo <- AggregateExpression(so,
                              assays = "RNA",
                              return.seurat = TRUE,
                              group.by = c("clinical_condition", "sample",
                                           "harmsnn_res.0.4"))
pb_pseudo$ident.cond <- paste0(pb_pseudo$harmsnn_res.0.4,
                               "_", pb_pseudo$clinical_condition)
Idents(pb_pseudo) <- "ident.cond"

pb_bulk.de <- list()
cell_counts <- table(Idents(pb_pseudo))
for (cl in unique(pb_pseudo$harmsnn_res.0.4)) {
    ident.1 <- paste0(cl, "_" , "Inapparent")
    ident.2 <- paste0(cl, "_" , "Hospitalized")
    if (!(ident.1 %in% names(cell_counts))) { next }
    if (!(ident.2 %in% names(cell_counts))) { next }
    markers <- FindMarkers(pb_pseudo, features = selgenes,
                ident.1 = ident.1, ident.2 = ident.2, test.use = "DESeq2",
                min.cells.group = 0)
    pb_bulk.de[[cl]] <- markers
}
```

```{r}
pb_signif_genes <- list()
for (cl in names(pb_bulk.de)) {
    markers <- pb_bulk.de[[cl]]
    pb_signif_markers <- markers[markers$p_val_adj <= 0.05, ]
    pb_signif_markers <- na.omit(pb_signif_markers)
    pb_signif_genes[[cl]] <- pb_signif_markers
}
print(pb_signif_genes)
pb_all_signif_genes <- unique(unlist(lapply(pb_signif_genes, rownames)))
```

```{r feature_plot_MAP3K8, fig.width=10, fig.height=6}
plt <- FeaturePlot(so, features = "IFI27",reduction = "umapharm",
            split.by="clinical_condition")
fname <- paste0(plots_dir, "Pb.feature_plot_IFI27.svg")
ggsave(filename = fname, plot = plt, device = "svg")
plt
```

# Session info

```{r}
sessionInfo()
```
