---
title: "Inden B cells | run ScMetabolism"
author: "Giorgio Gonnella"
date: 2024-08-27
output:
  html_document:
    theme: sandstone
params:
  prjpath: "/srv/baia/prj/subclinical_dengue_scrnaseq/"
  libpath: "/home/giorgio/R-pkg-Seurat5/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F, warning=F, echo=T)
.libPaths(c(params$libpath, .libPaths()))

library(Seurat)
library(scMetabolism)

analysis_root <- paste0(params$prjpath, "analysis-1/")

input_step_dir <- paste0(analysis_root, "steps/104.0.P.B.integration.harmony/")
input_var_dir <- paste0(input_step_dir, "results/vars/")
if (!dir.exists(input_var_dir)) {
  stop("Input variable directory does not exist: ", input_var_dir)
}

this_step_dir <- paste0(analysis_root, "steps/106.0.P.B.scMetabolism/")
if (!dir.exists(this_step_dir)) {
  stop("Current step directory does not exist: ", this_step_dir)
}
var_dir <- paste0(this_step_dir, "results/vars/")
dir.create(var_dir, showWarnings = FALSE, recursive = TRUE)
```

# Load data

```{r load_data, echo=FALSE}
so <- readRDS(file = paste0(input_var_dir, "integrated_so.rds"))
```

# Compute

```{r compute}
# This code can only run on HPC nodes, since it takes about 80 Gb of memory
countexp.Seurat <- sc.metabolism.Seurat(obj = so,
                                        method = "VISION", imputation = F,
                                        ncores = 2, metabolism.type = "KEGG")
```

# Save results

```{r save_results}
fname = paste0(var_dir, "scMetabolism_so.rds")
saveRDS(countexp.Seurat, file = fname)
```

# Session info

```{r session_info, echo=FALSE}
sessionInfo()
```
