---
title: "InDen | BCR analysis | CDR3 region"
author: "Giorgio Gonnella"
date: "2024-10-14"
output:
  html_document:
    theme: sandstone
params:
  prjpath: "/srv/baia/prj/subclinical_dengue_scrnaseq/"
  libpath: "/home/giorgio/R-pkg-Seurat5/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F, warning=F, echo=F)
.libPaths(c(params$libpath, .libPaths()))

library(Platypus)
library(ggplot2)
library(dplyr)

analysis_root <- paste0(params$prjpath, "analysis-1/")

input_step_dir <- paste0(analysis_root, "steps/110.0.P.B.BCR_analysis.platypus/")
input_var_dir <- paste0(input_step_dir, "results/vars/")
if (!dir.exists(input_var_dir)) {
  stop("Input variable directory does not exist: ", input_var_dir)
}

this_step_dir <- paste0(analysis_root, "steps/110.0.V.B.BCR_results/")
if (!dir.exists(this_step_dir)) {
  stop("Current step directory does not exist: ", this_step_dir)
}
plots_dir <- paste0(this_step_dir, "results/plots/")
tables_dir <- paste0(this_step_dir, "results/tables/")
dir.create(plots_dir, showWarnings = F, recursive = T)
dir.create(tables_dir, showWarnings = F, recursive = T)

helpers_dir = paste0(params$prjpath, "helpers/")
source(paste0(helpers_dir, "ggplot2_helpers.R"))
source(paste0(helpers_dir, "platypus_helpers.R"))
```

# Load data

The data after the post-filtering processing is loaded from file.

```{r load_vgm}
vgm <- readRDS(file = paste0(input_var_dir, "vgm.rds"))
vgm_HL <- readRDS(file = paste0(input_var_dir, "vgm_HL.rds"))
```

# VDJ and VJ CDR3 amino acid sequence lengths

## Absolute counts

```{r cdr3_aa_seqlength_vdj_abs}
plt <- ggplot(data.frame(condition=factor(vgm[["VDJ"]][["clinical_condition"]]),
                         numvalues=nchar(vgm[["VDJ"]]$VDJ_cdr3s_aa)),
       aes(x=numvalues, fill=condition)) + geom_bar(position="dodge") +
       xlab("VDJ CDR3 length (aa)") + ylab("Count") +
       theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5))+
       theme(legend.position="none") +
       scale_fill_manual(values=vgm[["GEX"]]@misc$cond_cols)
print(plt)
```

```{r}
data <- data.frame(
  condition = factor(vgm[["VDJ"]][["clinical_condition"]]),
  celltype = factor(vgm[["VDJ"]][["sample"]]),
  seqlength = nchar(vgm[["VDJ"]]$VDJ_cdr3s_aa)
)

data_counts <- data %>%
  group_by(celltype, condition, seqlength) %>%
  summarise(count = n())

plt <- ggplot(data_counts, aes(x=seqlength, y=count, fill=condition)) + 
  geom_bar(stat="identity", position="dodge") +
  xlab("VDJ CDR3 length (aa)") + 
  ylab("Count (log. scale)") +
  facet_wrap(~celltype) +
  theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5)) +
  scale_y_log10() +
  theme(legend.position="none") +
  scale_fill_manual(values=vgm[["GEX"]]@misc$cond_cols)

print(plt)
```

```{r cdr3_aa_seqlength_vj_abs}
plt <- ggplot(data.frame(condition=factor(vgm_HL[["VDJ"]][["clinical_condition"]]),
                         numvalues=nchar(vgm_HL[["VDJ"]]$VJ_cdr3s_aa)),
       aes(x=numvalues, fill=condition)) + geom_bar(position="dodge") +
       xlab("VJ CDR3 length (aa)") + ylab("Count") +
       theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5))+
       theme(legend.position="none") +
       scale_fill_manual(values=vgm_HL[["GEX"]]@misc$cond_cols)
print(plt)
```

```{r}
data <- data.frame(
  condition = factor(vgm_HL[["VDJ"]][["clinical_condition"]]),
  celltype = factor(vgm_HL[["VDJ"]][["sample"]]),
  seqlength = nchar(vgm_HL[["VDJ"]]$VJ_cdr3s_aa)
)

data_counts <- data %>%
  group_by(celltype, condition, seqlength) %>%
  summarise(count = n())

plt <- ggplot(data_counts, aes(x=seqlength, y=count, fill=condition)) +
  geom_bar(stat="identity", position="dodge") +
  xlab("VJ CDR3 length (aa)") + 
  ylab("Count (log. scale)") +
  facet_wrap(~celltype) +
  theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5)) +
  scale_y_log10() +
  theme(legend.position="none") +
  scale_fill_manual(values=vgm_HL[["GEX"]]@misc$cond_cols)

print(plt)
```

## Relative frequencies

```{r cdr3_aa_seqlength_vdj_rel}
data <- data.frame(
  condition = factor(vgm[["VDJ"]][["clinical_condition"]]),
  seqlength = nchar(vgm[["VDJ"]]$VDJ_cdr3s_aa)
)

# Calculate relative frequencies
data_relative <- data %>%
  group_by(condition, seqlength) %>%
  summarise(count = n()) %>%
  mutate(relative_count = count / sum(count))

# Plot relative frequencies
plt <- ggplot(data_relative, aes(x=seqlength, y=relative_count,
                                 fill=condition)) +
  geom_bar(stat="identity", position="dodge") +
  xlab("VDJ CDR3 length (aa)") +
  ylab("Relative Count") +
  theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual(values=vgm[["GEX"]]@misc$cond_cols)

#knitr::kable(data_relative)
print(plt)
```

```{r}
data <- data.frame(
  condition = factor(vgm[["VDJ"]][["clinical_condition"]]),
  celltype = factor(vgm[["VDJ"]][["sample"]]),
  seqlength = nchar(vgm[["VDJ"]]$VDJ_cdr3s_aa)
)

data_counts <- data %>%
  group_by(celltype, condition, seqlength) %>%
  summarise(count = n())

data_relative <- data_counts %>%
  mutate(relative_count = count / sum(count))

plt <- ggplot(data_relative, aes(x=seqlength, y=relative_count,
                                 fill=condition)) +
  geom_bar(stat="identity", position="dodge") +
  xlab("VDJ CDR3 length (aa)") +
  ylab("Relative Count") +
  facet_wrap(~celltype) +
  theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5)) +
  theme(legend.position="none") +
  scale_fill_manual(values=vgm[["GEX"]]@misc$cond_cols)

print(plt)
```

```{r cdr3_aa_seqlength_vj_rel}
data <- data.frame(
  condition = factor(vgm_HL[["VDJ"]][["clinical_condition"]]),
  seqlength = nchar(vgm_HL[["VDJ"]]$VJ_cdr3s_aa)
)

# Calculate relative frequencies
data_relative <- data %>%
  group_by(condition, seqlength) %>%
  summarise(count = n()) %>%
  mutate(relative_count = count / sum(count))

# Plot relative frequencies
plt <- ggplot(data_relative, aes(x=seqlength, y=relative_count,
                                 fill=condition)) +
  geom_bar(stat="identity", position="dodge") +
  xlab("VJ CDR3 length (aa)") +
  ylab("Relative Count") +
  theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual(values=vgm_HL[["GEX"]]@misc$cond_cols)

print(plt)
```

```{r}
data <- data.frame(
  condition = factor(vgm_HL[["VDJ"]][["clinical_condition"]]),
  celltype = factor(vgm_HL[["VDJ"]][["sample"]]),
  seqlength = nchar(vgm_HL[["VDJ"]]$VJ_cdr3s_aa)
)

data_counts <- data %>%
  group_by(celltype, condition, seqlength) %>%
  summarise(count = n())

data_relative <- data_counts %>%
  mutate(relative_count = count / sum(count))

plt <- ggplot(data_relative, aes(x=seqlength, y=relative_count,
                                 fill=condition)) +
  geom_bar(stat="identity", position="dodge") +
  xlab("VJ CDR3 length (aa)") +
  ylab("Relative Count") +
  facet_wrap(~celltype) +
  theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5)) +
  theme(legend.position="none") +
  scale_fill_manual(values=vgm_HL[["GEX"]]@misc$cond_cols)

print(plt)
```

# Most frequent CDR3 aa sequences

## Colored by celltype

```{r most_freq_CDR3s_vdj}
tab_plt <- most_freq_cdr3s_aa_plot(vgm[["VDJ"]], color_by = "celltype",
                                  cols = vgm$GEX@misc$fctype_mod_cols,
                              color_lbl = "Cell type",
                              group_col = "clinical_condition")
filename <- paste0(plots_dir, "most_freq_CDR3s_aa.vdj.svg")
ggsave(filename, tab_plt$plot, width = 10, height = 5)
tab_plt$plot
```

```{r most_freq_CDR3s_vj}
tab_plt <- most_freq_cdr3s_aa_plot(vgm_HL[["VDJ"]], color_by = "celltype",
                                  cols = vgm$GEX@misc$fctype_mod_cols,
                              color_lbl = "Cell type",
                              group_col = "clinical_condition",
                              use.VJ = TRUE)
filename <- paste0(plots_dir, "most_freq_CDR3s_aa.vj.svg")
ggsave(filename, tab_plt$plot, width = 10, height = 5)
```

## Colored by sample

```{r}
most_freq <- most_freq_cdr3s_aa_plot(vgm$VDJ, color_lbl = "Sample ID",
                                     color_by = "sample_name",
                                     cols = vgm$GEX@misc$sample_name_cols,
                                     group_col = "clinical_condition")
fname <- paste0(plots_dir, "B.most_freq_CDR3s_aa.VDJ.by_sample.svg")
ggsave(fname, most_freq$plot, device = "svg", width=3, height=2.6, scale=1.5)
print(most_freq$plot)

# common sequences
aaS <- most_freq$cdr3_usage_top[
          most_freq$cdr3_usage_top$clinical_condition ==
            "Subclinical", ]$VDJ_cdr3s_aa
aaH <- most_freq$cdr3_usage_top[
          most_freq$cdr3_usage_top$clinical_condition ==
            "Hospitalized", ]$VDJ_cdr3s_aa
intersection = intersect(aaS, aaH)
print(paste0("Common sequences between most frequent ",
             "Subclinical and Hospitalized (", length(intersection), ")"))
if (length(intersection) > 0) { print(intersection)}

for (celltype in unique(vgm[["VDJ"]]$celltype.abbrev)) {
  most_freq <- most_freq_cdr3s_aa_plot(vgm$VDJ, color_lbl = "Sample",
        sel_celltype = celltype, celltype_col = "celltype.abbrev",
        color_by = "sample_name", cols = vgm$GEX@misc$sample_name_cols,
        title="", group_col = "clinical_condition",
        short_title=T)
  most_freq$plot <- most_freq$plot +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank())

  celltype_sanitized <- gsub("[^[:alnum:]]", "_", celltype)
  fname <- paste0(plots_dir, "B.most_freq_CDR3s.VDJ.by_sample.",
                  celltype_sanitized, ".svg")
  ggsave(fname, most_freq$plot, device = "svg",
         width=4.5, height=2.6, scale=1.5)
  print(most_freq$plot)
}
```

# Shared CD3s sequences

```{r}
vj_cdr3s_aa_oh <- VDJ_overlap_sorted_heatmap(vgm_HL$VDJ, c("VJ_cdr3s_aa"),
                                             grouping.column = "sample_name",
                                             group.by = "clinical_condition",
                                             axis.label.size = 12,
                                             pvalues.label.size = 6)
plt <- vj_cdr3s_aa_oh[[1]]
fname <- paste0(plots_dir, "VJ_cdr3s_aa.overlap.svg")
ggsave(fname, plt)
print(plt)
```

```{r}
vdj_cdr3s_aa_oh <- VDJ_overlap_sorted_heatmap(vgm_HL$VDJ, c("VDJ_cdr3s_aa"),
                                              grouping.column = "sample_name",
                                              group.by = "clinical_condition",
                                              axis.label.size = 12,
                                              pvalues.label.size = 6)
plt <- vdj_cdr3s_aa_oh[[1]]
fname <- paste0(plots_dir, "VDJ_cdr3s_aa.overlap.svg")
ggsave(fname, plt)
print(plt)
```

```{r}
vdj_vj_cdr3s_aa_oh <- VDJ_overlap_sorted_heatmap(vgm_HL$VDJ,
                                          c("VDJ_cdr3s_aa", "VJ_cdr3s_aa"),
                                          grouping.column = "sample_name",
                                          group.by = "clinical_condition",
                                          axis.label.size = 12,
                                          pvalues.label.size = 6)
plt <- vdj_vj_cdr3s_aa_oh[[1]]
fname <- paste0(plots_dir, "VDJ_VJ_cdr3s_aa.overlap.svg")
ggsave(fname, plt)
print(plt)
```

## Shared sequence

```{r}
# more information on the only shared sequence
shared <- vdj_vj_cdr3s_aa_oh[[2]][25,]
cdr3s <- str_split(shared$items.overlapping, '/')
vdj_cdr3s <- cdr3s[[1]][[1]]
vj_cdr3s <- cdr3s[[1]][[2]]
shared_vdj <- subset(vgm_HL$VDJ, VDJ_cdr3s_aa == vdj_cdr3s)
shared_both <- subset(shared_vdj, VJ_cdr3s_aa == vj_cdr3s)
print(vdj_cdr3s)
print(vj_cdr3s)
print(table(shared_both$celltype, shared_both$sample_name))
```

# Session info

```{r}
sessionInfo()
```
