---
title: "InDen B cells | BCR sequencing analysis | SHM analysis"
author: "Giorgio Gonnella"
date: "2024-10-14"
output:
  html_document:
    theme: sandstone
params:
  prjpath: "/srv/baia/inden/"
  libpath: "/home/giorgio/R-pkg-Seurat5/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(Platypus)
library(ggplot2)
library(dplyr)

analysis_root <- paste0(params$prjpath, "analysis-1/")

input_step_dir <- paste0(analysis_root,
                         "steps/110.0.P.B.BCR_analysis.platypus/")
input_var_dir <- paste0(input_step_dir, "results/vars/")
if (!dir.exists(input_var_dir)) {
  stop("Input variable directory does not exist: ", input_var_dir)
}

this_step_dir <- paste0(analysis_root, "steps/110.0.V.B.BCR_results/")
if (!dir.exists(this_step_dir)) {
  stop("Current step directory does not exist: ", this_step_dir)
}
plots_dir <- paste0(this_step_dir, "results/plots/")
tables_dir <- paste0(this_step_dir, "results/tables/")
dir.create(plots_dir, showWarnings = F, recursive = T)
dir.create(tables_dir, showWarnings = F, recursive = T)

helpers_dir = paste0(params$prjpath, "helpers/")
source(paste0(helpers_dir, "ggplot2_helpers.R"))
source(paste0(helpers_dir, "platypus_helpers.R"))
```

## Load data

```{r load_vgm}
vgm_HL <- readRDS(file = paste0(input_var_dir, "vgm_HL.rds"))
```

# SHM analysis

```{r}
hpb_VDJ <- subset(vgm_HL$VDJ, pruned.labels_singleR_fine == 'Plasmablasts' & clinical_condition == 'Hospitalized')
hpb_VDJ$celltype <- droplevels(hpb_VDJ$celltype)
plot <- VDJ_SHM_boxplot(hpb_VDJ, group.by = "celltype",
                        group.colors = c("Non-proliferating plasmablasts" = "red", "Proliferating plasmablasts" = "red")) + 
  ggtitle("Hospitalized: Plasmablasts") +
  scale_x_discrete(labels = c("Non-proliferating plasmablasts" = "Non-proliferating", "Proliferating plasmablasts" = "Proliferating"))
fname <- paste0(plots_dir, "SHM_boxplot.H.Plasmablasts_pr_vs_nonpr.svg")
ggsave(fname, plot, device = "svg", width = 5, height = 6)
print(plot)

stats <- compute_SHM_stats(hpb_VDJ, "Plasmablasts", "celltype", "Non-proliferating plasmablasts", "Proliferating plasmablasts")
stats <- stats %>% mutate(adj_p_value = p.adjust(p_value, method = "BH"))
write.table(stats,
            file = paste0(tables_dir, "SHM_stats.H.Plasmablasts_pr_vs_nonpr.tsv"), row.names = FALSE)
```

```{r, fig.width=5, fig.height=6}
clinical_conditions_stats_table <- tibble()

# total
plot <- VDJ_SHM_boxplot(vgm_HL$VDJ, group.by = "clinical_condition",
                        group.colors = c("Subclinical" = "blue", "Hospitalized" = "red")) + 
  ggtitle("All B cells") +
  scale_x_discrete(labels = c("Subclinical" = "S", "Hospitalized" = "H")) +
  ylim(0, 80)

fname <- paste0(plots_dir, "SHM_boxplot.Total.svg")
ggsave(fname, plot, device = "svg", width = 5, height = 6)
print(plot)

total_stats <- compute_SHM_stats(vgm_HL$VDJ, "Total", "clinical_condition", "Subclinical", "Hospitalized")
clinical_conditions_stats_table <- bind_rows(clinical_conditions_stats_table, total_stats)

# cell types
vdj_subsets <- split(vgm_HL$VDJ, vgm_HL$VDJ$celltype)
for (label in names(vdj_subsets)) {
  subset_data <- vdj_subsets[[label]]

  plot <- VDJ_SHM_boxplot(vdj = subset_data, group.by = "clinical_condition", 
                          group.colors = c("Subclinical" = "blue", "Hospitalized" = "red")) +
    ggtitle(label) +
    scale_x_discrete(labels = c("Subclinical" = "S", "Hospitalized" = "H")) +
    ylim(0, 80)

  s_label <- gsub(" ", "_", label)
  s_label <- gsub("/", "_", s_label)
  fname <- paste0(plots_dir, "SHM_boxplot.", s_label, ".svg")
  ggsave(fname, plot, device = "svg", width = 5, height = 6)
  print(plot)

  subset_stats <- compute_SHM_stats(subset_data, label, "clinical_condition", "Subclinical", "Hospitalized")
  clinical_conditions_stats_table <- bind_rows(clinical_conditions_stats_table, subset_stats)
}

# Adjust p-values using the Benjamini-Hochberg (BH) method
clinical_conditions_stats_table <- clinical_conditions_stats_table %>%
  mutate(adj_p_value = p.adjust(p_value, method = "BH"))

write.table(clinical_conditions_stats_table,
            file = paste0(tables_dir, "SHM_stats.by_clinical_condition.tsv"), row.names = FALSE)
```

## Session Info

```{r}
sessionInfo()
```

