---
title: "InDen Project | B cells | Isolate Plasmablasts"
author: "Giorgio Gonnella"
date: 2024-08-16
output:
  html_document:
    theme: sandstone
params:
  pfx: "/srv/baia/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, comment = FALSE, echo = TRUE)

# required libraries
library(Seurat)
library(viridis)
library(ggplot2)
library(ggrepel)
library(ggExtra)
library(gplots)
library(RColorBrewer)
library(reshape2)
library(ggsci)
library(dplyr)
library(harmony)

prj_root <- paste0(params$pfx, "inden/")
analysis_root <- paste0(prj_root, "analysis-1/")

prev_step_dir <- paste0(analysis_root, "steps/108.0.P.B.split_plasmablasts/")
input_var_dir <- paste0(prev_step_dir, "results/vars/")

this_step_dir <- paste0(analysis_root, "steps/110.0.P.B.isolate_plasmablasts/")
var_dir <- paste0(this_step_dir, "results/vars/")
dir.create(var_dir, recursive = T)

```
```{r load_data, include = FALSE}
so <- readRDS(file = paste0(input_var_dir, "splitted_so.rds"))
```

# Isolate the cells

```{r isolate_emcd8}
Idents(so) <- so$pruned.labels_singleR_fine
Pb <- subset(so, idents=c("Plasmablasts"))
```

# Integration

```{r integration}
Pb <- RunHarmony(object = Pb, reduction.use = "pca",
                       group.by.vars = "orig.ident")
```

# UMAP

```{r umap}
myDims <- 1:40
Pb <- RunUMAP(object = Pb, dims = myDims,
                    reduction = "harmony", reduction.name = "umapharm")
```

# Clustering

```{r clustering}
reS <- c(0.2, 0.3, 0.4)
Pb <- FindNeighbors(Pb, dims = myDims, reduction = "harmony",
                          graph.name = "harmsnn")
Pb <- FindClusters(Pb, resolution = reS, graph.name = "harmsnn")
```

```{r select_resolution}
Pb@misc$sel_res <- 0.2
Pb@misc$sel_res_col <- paste0("harmsnn_res.", Pb@misc$sel_res)
```

## Saving data

```{r, echo=TRUE}
saveRDS(Pb, file = paste0(var_dir, "isolated_blasmablasts.rds"))
```
# Session info

```{r}
sessionInfo()
```
