---
title: "InDen T cells | Individual samples | First steps"
author: "Giorgio Gonnella; Sebastien Mella"
date: "2024-03-27"
output:
  html_document: default
params:
  prjpath: "/srv/baia/prj/subclinical_dengue_scrnaseq/"
  libpath: "/home/giorgio/R-pkg-Seurat5/"
  sample: NA
---

```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(message=F, warning=F, echo=F)
.libPaths(c(params$libpath, .libPaths()))

library(SingleCellExperiment)
library(scater)
library(Seurat)
library(robustbase)

if (is.na(params$sample)) {
  stop("Please provide a sample name")
}

analysis_root <- paste0(params$prjpath, "analysis-1/")

data_dir <- paste0(params$prjpath, "cellranger/results/")
sample_data_dir <- paste0(data_dir, params$sample, "/")
if (!dir.exists(sample_data_dir)) {
  stop("Sample data directory does not exist: ", sample_data_dir)
}
h5_input_dir <-
  paste0(sample_data_dir, "per_sample_outs/", params$sample, "/count/")
if (!dir.exists(h5_input_dir)) {
  stop("H5 input directory does not exist: ", h5_input_dir)
}

this_step_dir <- paste0(analysis_root, "steps/001.0.P.T.create_seurat_obj/")
if (!dir.exists(this_step_dir)) {
  stop("Current step directory does not exist: ", this_step_dir)
}

var_dir <- paste0(this_step_dir, "results/vars/")
dir.create(var_dir, showWarnings = FALSE, recursive = TRUE)

helpers_dir <- paste0(params$prjpath, "helpers/")
source(paste0(helpers_dir, "qc_helpers.R"))
```

# Create Seurat object from Cellranger filtered h5 matrix

```{r read10X_h5}
# the file can be called differently depending on Cellranger version:
h5fnc6 = paste0(h5_input_dir, "sample_feature_bc_matrix.h5")
h5fnc7 = paste0(h5_input_dir, "sample_filtered_feature_bc_matrix.h5")
if (file.exists(h5fnc6)) {
  h5_fname <- h5fnc6
} else if (file.exists(h5fnc7)) {
  h5_fname <- h5fnc7
} else {
  stop("No sample filtered h5 file found in ", h5_input_dir)
}
data <- Read10X_h5(filename = h5_fname)
```

```{r create_so}
so_name <- paste0("TC_SC03_S", sub("_", "", sub("sample_", "", params$sample)),
                  "_so")
so <- CreateSeuratObject(counts = data, project = so_name,
                         min.cells = 0, min.features = 0)
rm(data)
```

# Compute QC measures

## Mitochondrial genes

```{r percent_mito}
mito_genes <- grep("^MT-", rownames(so@assays$RNA$counts), value = TRUE)
so <- compute_percent_mito(so, mito_genes)
```

## QC with scater

```{r qc_scater}
sce <- SingleCellExperiment(assays = list(counts = so@assays$RNA$counts))
is.mito <- grepl("^MT-", rownames(sce))
qcstats <- perCellQCMetrics(sce, subsets=list(Mito=is.mito))
filt_ad <- data.frame(
  qc.lib.low = isOutlier(qcstats$sum, log = TRUE, type = "lower"),
  qc.lib.high = isOutlier(qcstats$sum, log = FALSE, type = "higher", nmads = 4),
  qc.nexprs.low = isOutlier(qcstats$detected, log = TRUE, type = "lower"),
  qc.nexprs.high =
    isOutlier(qcstats$detected, log = FALSE, type = "higher", nmads = 4),
  qc.mito.high =
    isOutlier(qcstats$subsets_Mito_percent, log = FALSE, type = "higher")
)
qcstats <- cbind(as.data.frame(qcstats), filt_ad)
# rename sum to scater_qcstats_sum
colnames(qcstats)[colnames(qcstats) == "sum"] <- "scater_qcstats_sum"
# rename detected to scater_qcstats_detected
colnames(qcstats)[colnames(qcstats) == "detected"] <- "scater_qcstats_detected"
so@meta.data <- cbind(so@meta.data, qcstats)
```

## QC with robustbase

```{r qc_robustbase}
set.seed(745)
stats <- cbind(log10(so$nCount_RNA),
               log10(so$nFeature_RNA),
               so$percent.mito)
outlying <- adjOutlyingness(stats, only.outlyingness = TRUE)
multi.outlier <- isOutlier(outlying, type = "higher")
so$multi.outlier <- multi.outlier
```

## Removing redundant QC information

```{r rm_redundant_qc}
so@meta.data <- so@meta.data[,c("orig.ident","nCount_RNA","nFeature_RNA",
                                "scater_qcstats_sum","scater_qcstats_detected",
                                "subsets_Mito_sum","subsets_Mito_detected",
                                "percent.mito","percent.mito.cl","qc.lib.low",
                                "qc.lib.high","qc.nexprs.low","qc.nexprs.high",
                                "qc.mito.high", "multi.outlier")]
```

# VDJ info

```{r fetching_vdj_info}
vdj_info <- read.csv(file = paste0(sample_data_dir, "per_sample_outs/",
                                   params$sample, "/vdj_t/",
                                   "filtered_contig_annotations.csv"),
                     stringsAsFactors = FALSE)
so$has_prod_vdj <- rownames(so@meta.data) %in% vdj_info$barcode
```

# Cell cycle scoring

```{r cell_cycle_scoring}
so <- test_cell_cycle_effect(so, so_name,
                             s_genes = cc.genes.updated.2019$s.genes,
                             g2m_genes = cc.genes.updated.2019$g2m.genes)
```

# CD3 positivity

```{r CD3_positivity}
so$CD3_plus <- so@assays$RNA$counts["CD3E",] > 0 |
               so@assays$RNA$counts["CD3D",] > 0 |
               so@assays$RNA$counts["CD3G",] > 0
```

# Saving

```{r saving, echo=T}
saveRDS(so, paste0(var_dir, params$sample, "_so_initial.rds"))
```

# Session info

```{r session_info, echo=F}
sessionInfo()
```
