---
title: "Inden Project | T cells, after splitting | scMetabolism"
author: "Giorgio Gonnella"
date: 2024-08-29
output:
  html_document:
    theme: sandstone
params:
  pfx: "/srv/baia/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, comment = FALSE, echo = TRUE)

library(Seurat)
library(viridis)
library(ggplot2)
library(ggrepel)
library(ggExtra)
library(gplots)
library(RColorBrewer)
library(reshape2)
library(ggsci)
library(dplyr)
library(scProportionTest)
library(pheatmap)
library(gridExtra)

prj_root <- paste0(params$pfx, "inden/")
analysis_root <- paste0(prj_root, "analysis-1/")

input_step_dir <- paste0(analysis_root, "steps/008.0.P.T.split_CD8EM/")
input_var_dir <- paste0(input_step_dir, "results/vars/")

this_step_dir <- paste0(analysis_root, "steps/008.0.V.T.splitted_CD8EM/")
tables_outdir <- paste0(this_step_dir, "results/tables/")
plots_outdir <- paste0(this_step_dir, "results/plots/")
dir.create(tables_outdir, recursive = T)
dir.create(plots_outdir, recursive = T)

gg_scripts_dir <- paste0(prj_root, "helpers/")
source(paste0(gg_scripts_dir, "combined_proportion_plot.R"))
```

```{r load_data, echo=FALSE}
TC_SC03_alltcells_met <- readRDS(file = paste0(input_var_dir, "so_scMetabolism.rds"))
```

```{r}
#
# NOTE: This code can be removed, when the _scMetabolism.rds is computed again
#

levels(TC_SC03_alltcells_met$pruned.labels_singleR_fine) <- c(levels(TC_SC03_alltcells_met$pruned.labels_singleR_fine), "Gamma-delta T cells")
TC_SC03_alltcells_met$pruned.labels_singleR_fine[TC_SC03_alltcells_met$pruned.labels_singleR_fine == "Vd2 gd T cells"] <- "Gamma-delta T cells"
TC_SC03_alltcells_met$pruned.labels_singleR_fine[TC_SC03_alltcells_met$pruned.labels_singleR_fine == "Non-Vd2 gd T cells"] <- "Gamma-delta T cells"
TC_SC03_alltcells_met$pruned.labels_singleR_fine <- droplevels(TC_SC03_alltcells_met$pruned.labels_singleR_fine)

TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev <-
  levels(TC_SC03_alltcells_met$pruned.labels_singleR_fine)
names(TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev) <-
  levels(TC_SC03_alltcells_met$pruned.labels_singleR_fine)

TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[[
    "Naive CD4 T cells"]] <- "CD4+ Naive"
TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[[
    "Th1 cells"]] <- "Th1"
TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[[
    "Th1/Th17 cells"]] <- "Th1/Th17"
TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[[
    "Th17 cells"]] <- "Th17"
TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[[
    "Th2 cells"]] <- "Th2"
TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[[
    "Follicular helper T cells"]] <- "Tfh"
TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[[
    "T regulatory cells"]] <- "Tregs"
TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[[
    "Terminal effector CD4 T cells"]] <- "CD4+ TEMRA"
TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[[
    "Naive CD8 T cells"]] <- "CD8+ Naive"
TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[[
    "Central memory CD8 T cells"]] <- "CD8+ CM"
TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[[
    "Effector memory CD8 T cells"]] <- "CD8+ EM"
TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[[
    "Terminal effector CD8 T cells"]] <- "CD8+ TEMRA"
TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[[
    "MAIT cells"]] <- "MAIT"
TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[[
    "Gamma-delta T cells"]] <- "GD"

TC_SC03_alltcells_met$pruned.labels_singleR_fine.abbrev <-
  factor(as.vector(TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[
    TC_SC03_alltcells_met$pruned.labels_singleR_fine]),
    levels = TC_SC03_alltcells_met@misc$pruned.labels_singleR_fine.abbrev[
      levels(TC_SC03_alltcells_met$pruned.labels_singleR_fine)])
```

```{r}
library(scMetabolism)
library(wesanderson)
library(ggplot2)
library(patchwork)
library(grid)
library(cowplot)

# this modifies the original function to use umapharm and allow split.by

scMetabolismDimplot <- function(obj, pathway, split.by = NULL, ncol = NULL, combine = TRUE) {
  size <- 0.2
  cat("\nPlease Cite: \nYingcheng Wu, Qiang Gao, et al. Cancer Discovery. 2021. \nhttps://pubmed.ncbi.nlm.nih.gov/34417225/   \n\n")
  
  # UMAP coordinates
  umap.loc <- obj@reductions$umapharm@cell.embeddings
  row.names(umap.loc) <- colnames(obj)
  
  # Metabolism signature expression
  signature_exp <- obj@assays$METABOLISM$score
  input.pathway <- pathway
  signature_ggplot <- data.frame(umap.loc, t(signature_exp[input.pathway, ]))
  
  # Define axis limits for consistency
  xlim <- range(signature_ggplot$umapharm_1)
  ylim <- range(signature_ggplot$umapharm_2)
  color_lim <- range(signature_ggplot[, 3])

  # Add splitting by group
  if (!is.null(split.by)) {
    split <- FetchData(object = obj, vars = split.by, clean = TRUE)[split.by]
    signature_ggplot <- cbind(signature_ggplot, split)
  }
  
  # Plotting
  pal <- wes_palette("Zissou1", 100, type = "continuous")

  # Create individual plots for each split
  plots <- lapply(unique(signature_ggplot[[split.by]]), function(group) {
    data_subset <- signature_ggplot[signature_ggplot[[split.by]] == group, ]
    ggplot(data = data_subset, aes(x = umapharm_1, y = umapharm_2, color = data_subset[, 3])) + 
      geom_point(size = size) + 
      scale_fill_gradientn(colours = pal, limits = color_lim) + 
      scale_color_gradientn(colours = pal, limits = color_lim) + 
      labs(color = input.pathway, title = group) + 
      xlab("umapharm_1") + 
      ylab("umapharm_2") + 
      xlim(xlim) + 
      ylim(ylim) + 
      theme(aspect.ratio = 1) + 
      theme(panel.grid.major = element_blank(), 
            panel.grid.minor = element_blank(), 
            panel.background = element_blank(), 
            axis.line = element_line(colour = "black"),
            legend.position = "none")
  })

  # Generate the combined plot without legend
  combined_plot <- wrap_plots(plots, ncol = ncol %||% length(unique(signature_ggplot[[split.by]])))

  # Create the legend plot from the first plot
  legend_plot <- ggplot(signature_ggplot, aes(x = umapharm_1, y = umapharm_2, color = signature_ggplot[, 3])) +
    geom_point(size = size) +
    scale_fill_gradientn(colours = pal, limits = color_lim) + 
    scale_color_gradientn(colours = pal, limits = color_lim) + 
    labs(color = input.pathway) +
    theme(legend.position = "right")

  # Extract the legend
  tmp <- ggplot_gtable(ggplot_build(legend_plot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]

  # Combine the plot with the legend
  combined_plot_with_legend <- plot_grid(combined_plot, NULL, legend, ncol = 3, rel_widths = c(0.55, 0.02, 0.2))

  # Return the final plot
  return(combined_plot_with_legend)
}

pathways = c("Glycolysis / Gluconeogenesis", "Oxidative phosphorylation",
             "Citrate cycle (TCA cycle)")

for (pathway in pathways) {
  dimplot <- scMetabolismDimplot(TC_SC03_alltcells_met, pathway, "clinical_condition")
  sanitized_label <- gsub(" ", "_", pathway)
  sanitized_label <- gsub("[(]", "", sanitized_label)
  sanitized_label <- gsub("[)]", "", sanitized_label)
  sanitized_label <- gsub("/", "_", sanitized_label)
  sanitized_label <- gsub("__", "_", sanitized_label)
  sanitized_label <- gsub("__", "_", sanitized_label)
  fname <- paste0(plots_outdir, "scMetabolism.Dimplot.T.",
                  gsub(" ", "_", sanitized_label), ".svg")
  ggsave(fname, plot = dimplot, device = "svg")
  print(dimplot)
}

dotplot <- DotPlot.metabolism(obj = TC_SC03_alltcells_met, pathway = pathways,
                              phenotype = "pruned.labels_singleR_fine.abbrev",
                              norm = "y")
dotplot <- dotplot + scale_x_discrete(limits = levels(TC_SC03_alltcells_met$pruned.labels_singleR_fine.abbrev))
dotplot <- dotplot + xlab(NULL) + ylab(NULL) + labs(color = "Score") + labs(size = "Score")
fname <- paste0(plots_outdir, "scMetabolism.Dotplot.T.svg")
ggsave(fname, plot = dotplot, device = "svg")
print(dotplot)

```

# Session info

```{r session_info, echo=FALSE}
sessionInfo()
```
