---
title: "Inden Project | T cells, after splitting | Selected analyses"
author: "Giorgio Gonnella"
date: 2024-08-29
output:
  html_document:
    theme: sandstone
params:
  pfx: "/srv/baia/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = F, warning = F, comment = F, echo = T)

library(Seurat)
library(viridis)
library(ggplot2)
library(ggrepel)
library(ggExtra)
library(gplots)
library(RColorBrewer)
library(reshape2)
library(ggsci)
library(dplyr)
library(scProportionTest)
library(pheatmap)
library(gridExtra)

prj_root <- paste0(params$pfx, "inden/")
analysis_root <- paste0(prj_root, "analysis-1/")

input_step_dir <- paste0(analysis_root, "steps/008.0.P.T.split_CD8EM/")
input_var_dir <- paste0(input_step_dir, "results/vars/")

this_step_dir <- paste0(analysis_root, "steps/008.0.V.T.splitted_CD8EM/")
tables_outdir <- paste0(this_step_dir, "results/tables/")
plots_outdir <- paste0(this_step_dir, "results/plots/")
dir.create(tables_outdir, recursive = T)
dir.create(plots_outdir, recursive = T)

gg_scripts_dir <- paste0(prj_root, "helpers/")
source(paste0(gg_scripts_dir, "combined_proportion_plot.R"))
source(paste0(gg_scripts_dir, "dimplot_helpers.R"))
```

```{r load_data, echo=FALSE}
so <- readRDS(file = paste0(input_var_dir, "splitted_CD8EM_so.rds"))
```

# Splitted UMAP

```{r single_cell_types_umap, fig.width=8, fig.height=5, echo=F}
celltype1 <- "Proliferating effector memory CD8 T cells"
celltype2 <- "Non-proliferating effector memory CD8 T cells"
plt <- two_groups_dimplot(so, celltype1, celltype2,
                          "pruned.labels_singleR_fine.mod",
                          group_names = c("Proliferating", "Non-prolif."),
                          split_by = "clinical_condition")
fname = paste0(plots_outdir, "umap.by_cond.effectorCD8_splitted.svg")
ggsave(fname, plot = plt, device = "svg", width = 8, height = 5)
plt
```

# Cell type distribution

## Absolute counts

Table

```{r table_cond_per_fine_celltypes_abs_file, echo=F}
write.table(as.data.frame.matrix(table(
  so$pruned.labels_singleR_fine.mod,
  so$clinical_condition)),
  file = paste0(tables_outdir, "table_cond_per_fine_celltypes_abs.tsv"),
  sep = "\t")
```

Plot

```{r}
cell_type_counts <- so@meta.data %>%
  group_by(pruned.labels_singleR_fine.mod, clinical_condition) %>%
  summarise(count = n()) %>%
  ungroup()

cell_type_counts$pruned.labels_singleR_fine.mod <-
  factor(cell_type_counts$pruned.labels_singleR_fine.mod,
         levels = levels(so$pruned.labels_singleR_fine.mod))
```

```{r}
plt1 <- ggplot(cell_type_counts, aes(x = count,
                                     y = pruned.labels_singleR_fine.mod,
                                     fill = clinical_condition)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(x = "Count", y = "Cell Type",
       title = "Frequency of Cell Types by Condition") +
  scale_fill_manual(values = so@misc$cond_cols) +
  theme(axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12))
print(plt1)
```

## Relative counts

Table

```{r table_cond_per_fine_celltypes_file, echo=F}
write.table(as.data.frame.matrix(round(prop.table(table(
  so$pruned.labels_singleR_fine.mod,
  so$clinical_condition), margin = 2)*100, digits = 2)),
  file = paste0(tables_outdir, "table_cond_per_fine_celltypes.tsv"), sep = "\t")
```

Plot

```{r}
total_counts <- cell_type_counts %>%
  group_by(clinical_condition) %>%
  summarise(total = sum(count))

relative_counts <- cell_type_counts %>%
  left_join(total_counts, by = "clinical_condition") %>%
  mutate(relative_count = count / total) %>%
  select(clinical_condition, pruned.labels_singleR_fine.mod, relative_count)
```

```{r}
plt2 <- ggplot(relative_counts, aes(x = relative_count,
                                    y = pruned.labels_singleR_fine.mod,
                                    fill = clinical_condition)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(x = "Proportion", y = "Cell Type",
       title = "Relative Frequency of Cell Types by Condition") +
  scale_fill_manual(values = so@misc$cond_cols) +
  theme(axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12))
print(plt2)
```

# Proportion test

## Run test

```{r singleR_proportion_test, echo=T}
so_su <- sc_utils(so)
prop_test <- permutation_test(so_su,
                   cluster_identity = "pruned.labels_singleR_fine.mod.abbrev",
                   sample_1 = "Subclinical", sample_2 = "Hospitalized",
                   sample_identity = "clinical_condition",
                   n_permutations = 1000)
```

## Plot

```{r proportion_plot, fig.width=8, fig.height=8, echo=F}
so$cell_group <- NA
for (group in names(so@misc$fctype_group)) {
  so$cell_group <-
    ifelse(so$pruned.labels_singleR_fine %in%
           so@misc$fctype_group[[group]],
           group, so$cell_group)
}

prop_test@meta_data$cell_group <- NA
for (group in names(so@misc$fctype_group)) {
  prop_test@meta_data$cell_group <-
    ifelse(prop_test@meta_data$pruned.labels_singleR_fine %in%
           so@misc$fctype_group[[group]],
           group, prop_test@meta_data$cell_group)
}

plt <- grouped_combined_permutation_test_plot(so, prop_test,
            "pruned.labels_singleR_fine.mod.abbrev", "cell_group",
            "clinical_condition", "Clinical Condition", so@misc$cond_cols,
            so@misc$ctg_backcols)

fname <- paste0(plots_outdir, "singleR_proportion_test.svg")
ggsave(fname, plot = plt, device = "svg")
plt
```

## Table

```{r prop_test_results, echo=F}
cell_order <- c("Th17", "Th2", "Th1", "Th1/Th17",
                "Naive CD4", "T reg.", "Follicular helper",
                "TE CD4", "Naive CD8", "CM CD8",
                "TE CD8", "Prolif. EM CD8",
                "Non-prolif. EM CD8", "Vd2 gd", "Non-Vd2 gd",
                "MAIT")

results <- prop_test@results$permutation %>%
  mutate(clusters =
         factor(prop_test@results$permutation$clusters,
                levels = cell_order)) %>%
  arrange(clusters)
write.table(results,
            file = paste0(tables_outdir, "singleR_proportion_test.tsv"),
            sep = "\t", row.names = F)
```

# Session info

```{r session_info, echo=FALSE}
sessionInfo()
```
