---
title: "Inden T cells | Selected genes expression heatmap"
author: "Giorgio Gonnella"
date: 2024-08-20
output:
  html_document:
    theme: sandstone
params:
  prjpath: "/srv/baia/prj/subclinical_dengue_scrnaseq/"
  libpath: "/home/giorgio/R-pkg-Seurat5/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F, warning=F, echo=F)
.libPaths(c(params$libpath, .libPaths()))

library(Seurat)

analysis_root <- paste0(params$prjpath, "analysis-1/")

input_step_dir <- paste0(analysis_root, "steps/007.0.P.T.compute_de/")
input_var_dir <- paste0(input_step_dir, "results/vars/")
if (!dir.exists(input_var_dir)) {
  stop("Input variable directory does not exist: ", input_var_dir)
}

this_step_dir <- paste0(analysis_root, "steps/007.0.V.T.de_results/")
if (!dir.exists(this_step_dir)) {
  stop("Current step directory does not exist: ", this_step_dir)
}

plots_outdir <- paste0(this_step_dir, "results/plots/selected_genes_heatmap/")
dir.create(plots_outdir, recursive = T, showWarnings = F)

helpers_dir <- paste0(params$prjpath, "helpers/")
source(paste0(helpers_dir, "de_helpers.R"))
```

```{r load_data, echo=FALSE}
so <- readRDS(file = paste0(input_var_dir, "so_w_deseq.rds"))
```

```{r define_goi}
genes_of_interest <- c("RAB30", "IFNG", "TNF",                 # cytokine production
                       "GZMA", "GZMB", "GZMK", "PRF1", "FAS",  # cytotoxicity
                       "MKI67",                                # proliferation
                       "HAVCR2", "TIGIT", "LAG3",              # exhaustion
                       "PDCD1", "CTLA4",                       # immune checkpoint regulation
                       "IRF1", "IFITM3", "IFIT2")              # IFN response
```

```{r}
res = cmpexpr_by_group(so, genes_of_interest, "clinical_condition",
                      "pruned.labels_singleR_fine.mod")

print(res)
```

```{r setup_celltypes_order_and_labels_split}
celltypes1 <- c("Proliferating effector memory CD8 T cells", "Non-proliferating effector memory CD8 T cells")
names(celltypes1) <- c("Prolif. CD8+ TEM", "Non-prolif. CD8+ TEM")
```

```{r setup_celltypes_order_and_labels_other}
celltypes2 <- c("Th1 cells", "Th1/Th17 cells", "Th17 cells",
               "Th2 cells", "Follicular helper T cells", "T regulatory cells", "Terminal effector CD4 T cells",
               "Central memory CD8 T cells", "Effector memory CD8 T cells", "Terminal effector CD8 T cells",
               "MAIT cells", "Gamma-delta T cells")
names(celltypes2) <- c("Th1", "Th1/Th17", "Th17", "Th2", "TFH", "Tregs", "CD4+ TEMRA",
                      "CD8+ TCM", "CD8+ TEM", "CD8+ TEMRA", "MAIT", "GD")
```

```{r heatmap_split, fig.width=6, fig.height=6}
plt1 <- DE_selected_genes_heatmap(so@misc$de$all, genes_of_interest,
              paste0(plots_outdir, "heatmap_prolif_CD8TEM.pdf"),
              cell_types = celltypes1, max_abs_value = 2.5, add_stars=T)
print(plt1)
```

```{r heatmap_other, fig.width=6, fig.height=6}
plt2 <- DE_selected_genes_heatmap(so@misc$de$all, genes_of_interest,
              paste0(plots_outdir, "heatmap_T_subtypes.pdf"),
              cell_types = celltypes2, max_abs_value = 2.5, add_stars=T)
print(plt2)
```

# Session info

```{r session_info, echo=FALSE}
sessionInfo()
```
