#!/usr/bin/env bash

if [ $# -lt 1 ]; then
  echo "Knit a Rmd to HTML" > /dev/stderr
  echo "Usage: knit2html <Rmdfile> [param1=value1] [param2=value2] ..." > /dev/stderr
  exit 1
elif [ ! -e "$1" ]; then
  echo "File does not exist: $1" > /dev/stderr
  exit 1
fi

RMD_FILE=$1
shift  # Remove RMD_FILE from the positional parameters

TIME_FILE="${RMD_FILE%.*}.time"

# Initialize an empty string to hold the R parameters
R_PARAMS="list("

# Loop through the remaining arguments
for ARG in "$@"; do
  KEY="${ARG%=*}"
  VALUE="${ARG#*=}"
  R_PARAMS+="$KEY='$VALUE', "
done

# Remove the trailing comma and space, and close the list
R_PARAMS="${R_PARAMS%, })"

/usr/bin/time -o "$TIME_FILE" \
  Rscript -e "rmarkdown::render('$RMD_FILE', output_format='html_document', params=$R_PARAMS)"
