---
title: "InDen | BCR analysis | CDR3 region"
author: "Giorgio Gonnella"
date: "2024-10-14"
output:
  html_document:
    theme: sandstone
params:
  pfx: "/srv/baia/"
  libpath: "/home/giorgio/R-pkg-Seurat5/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F, warning=F, echo=F)
.libPaths(c(params$libpath, .libPaths()))

library(Platypus)
library(ggplot2)
library(dplyr)

prj_root <- paste0(params$pfx, "inden/")
analysis_root <- paste0(prj_root, "analysis-1/")

input_step_dir <- paste0(analysis_root, "steps/113.0.P.B.BCR_analysis.platypus/")
input_var_dir <- paste0(input_step_dir, "results/vars/")
if (!dir.exists(input_var_dir)) {
  stop("Input variable directory does not exist: ", input_var_dir)
}

this_step_dir <- paste0(analysis_root, "steps/113.0.V.B.BCR_results/")
if (!dir.exists(this_step_dir)) {
  stop("Current step directory does not exist: ", this_step_dir)
}
plots_dir <- paste0(this_step_dir, "results/plots/")
tables_dir <- paste0(this_step_dir, "results/tables/")
dir.create(plots_dir, showWarnings = F, recursive = T)
dir.create(tables_dir, showWarnings = F, recursive = T)

helpers_dir = paste0(prj_root, "helpers/")
source(paste0(helpers_dir, "ggplot2_helpers.R"))
source(paste0(helpers_dir, "platypus_helpers.R"))
```

# Load data

The data after the post-filtering processing is loaded from file.

```{r load_vgm}
vgm <- readRDS(file = paste0(input_var_dir, "vgm.rds"))
vgm_HL <- readRDS(file = paste0(input_var_dir, "vgm_HL.rds"))
```

# VDJ and VJ CDR3 amino acid sequence lengths

## Absolute counts

```{r cdr3_aa_seqlength_vdj_abs}
plt <- ggplot(data.frame(condition=factor(vgm[["VDJ"]][["clinical_condition"]]),
                         numvalues=nchar(vgm[["VDJ"]]$VDJ_cdr3s_aa)),
       aes(x=numvalues, fill=condition)) + geom_bar(position="dodge") +
       xlab("VDJ CDR3 length (aa)") + ylab("Count") +
       theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5))+
       theme(legend.position="none") +
       scale_fill_manual(values=vgm[["GEX"]]@misc$cond_cols)
print(plt)
```

```{r}
data <- data.frame(
  condition = factor(vgm[["VDJ"]][["clinical_condition"]]),
  celltype = factor(vgm[["VDJ"]][["sample"]]),
  seqlength = nchar(vgm[["VDJ"]]$VDJ_cdr3s_aa)
)

data_counts <- data %>%
  group_by(celltype, condition, seqlength) %>%
  summarise(count = n())

plt <- ggplot(data_counts, aes(x=seqlength, y=count, fill=condition)) + 
  geom_bar(stat="identity", position="dodge") +
  xlab("VDJ CDR3 length (aa)") + 
  ylab("Count (log. scale)") +
  facet_wrap(~celltype) +
  theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5)) +
  scale_y_log10() +
  theme(legend.position="none") +
  scale_fill_manual(values=vgm[["GEX"]]@misc$cond_cols)

print(plt)
```

```{r cdr3_aa_seqlength_vj_abs}
plt <- ggplot(data.frame(condition=factor(vgm_HL[["VDJ"]][["clinical_condition"]]),
                         numvalues=nchar(vgm_HL[["VDJ"]]$VJ_cdr3s_aa)),
       aes(x=numvalues, fill=condition)) + geom_bar(position="dodge") +
       xlab("VJ CDR3 length (aa)") + ylab("Count") +
       theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5))+
       theme(legend.position="none") +
       scale_fill_manual(values=vgm_HL[["GEX"]]@misc$cond_cols)
print(plt)
```

```{r}
data <- data.frame(
  condition = factor(vgm_HL[["VDJ"]][["clinical_condition"]]),
  celltype = factor(vgm_HL[["VDJ"]][["sample"]]),
  seqlength = nchar(vgm_HL[["VDJ"]]$VJ_cdr3s_aa)
)

data_counts <- data %>%
  group_by(celltype, condition, seqlength) %>%
  summarise(count = n())

plt <- ggplot(data_counts, aes(x=seqlength, y=count, fill=condition)) +
  geom_bar(stat="identity", position="dodge") +
  xlab("VJ CDR3 length (aa)") + 
  ylab("Count (log. scale)") +
  facet_wrap(~celltype) +
  theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5)) +
  scale_y_log10() +
  theme(legend.position="none") +
  scale_fill_manual(values=vgm_HL[["GEX"]]@misc$cond_cols)

print(plt)
```

## Relative frequencies

```{r cdr3_aa_seqlength_vdj_rel}
data <- data.frame(
  condition = factor(vgm[["VDJ"]][["clinical_condition"]]),
  seqlength = nchar(vgm[["VDJ"]]$VDJ_cdr3s_aa)
)

# Calculate relative frequencies
data_relative <- data %>%
  group_by(condition, seqlength) %>%
  summarise(count = n()) %>%
  mutate(relative_count = count / sum(count))

# Plot relative frequencies
plt <- ggplot(data_relative, aes(x=seqlength, y=relative_count,
                                 fill=condition)) +
  geom_bar(stat="identity", position="dodge") +
  xlab("VDJ CDR3 length (aa)") +
  ylab("Relative Count") +
  theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual(values=vgm[["GEX"]]@misc$cond_cols)

#knitr::kable(data_relative)
print(plt)
```

```{r}
data <- data.frame(
  condition = factor(vgm[["VDJ"]][["clinical_condition"]]),
  celltype = factor(vgm[["VDJ"]][["sample"]]),
  seqlength = nchar(vgm[["VDJ"]]$VDJ_cdr3s_aa)
)

data_counts <- data %>%
  group_by(celltype, condition, seqlength) %>%
  summarise(count = n())

data_relative <- data_counts %>%
  mutate(relative_count = count / sum(count))

plt <- ggplot(data_relative, aes(x=seqlength, y=relative_count,
                                 fill=condition)) +
  geom_bar(stat="identity", position="dodge") +
  xlab("VDJ CDR3 length (aa)") +
  ylab("Relative Count") +
  facet_wrap(~celltype) +
  theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5)) +
  theme(legend.position="none") +
  scale_fill_manual(values=vgm[["GEX"]]@misc$cond_cols)

print(plt)
```

```{r cdr3_aa_seqlength_vj_rel}
data <- data.frame(
  condition = factor(vgm_HL[["VDJ"]][["clinical_condition"]]),
  seqlength = nchar(vgm_HL[["VDJ"]]$VJ_cdr3s_aa)
)

# Calculate relative frequencies
data_relative <- data %>%
  group_by(condition, seqlength) %>%
  summarise(count = n()) %>%
  mutate(relative_count = count / sum(count))

# Plot relative frequencies
plt <- ggplot(data_relative, aes(x=seqlength, y=relative_count,
                                 fill=condition)) +
  geom_bar(stat="identity", position="dodge") +
  xlab("VJ CDR3 length (aa)") +
  ylab("Relative Count") +
  theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual(values=vgm_HL[["GEX"]]@misc$cond_cols)

print(plt)
```

```{r}
data <- data.frame(
  condition = factor(vgm_HL[["VDJ"]][["clinical_condition"]]),
  celltype = factor(vgm_HL[["VDJ"]][["sample"]]),
  seqlength = nchar(vgm_HL[["VDJ"]]$VJ_cdr3s_aa)
)

data_counts <- data %>%
  group_by(celltype, condition, seqlength) %>%
  summarise(count = n())

data_relative <- data_counts %>%
  mutate(relative_count = count / sum(count))

plt <- ggplot(data_relative, aes(x=seqlength, y=relative_count,
                                 fill=condition)) +
  geom_bar(stat="identity", position="dodge") +
  xlab("VJ CDR3 length (aa)") +
  ylab("Relative Count") +
  facet_wrap(~celltype) +
  theme(plot.title.position = "plot", plot.title = element_text(hjust = 0.5)) +
  theme(legend.position="none") +
  scale_fill_manual(values=vgm_HL[["GEX"]]@misc$cond_cols)

print(plt)
```

# Most frequent CDR3 sequences

```{r most_freq_CDR3s_vdj}
tab_plt <- most_freq_cd3s_aa_plot(vgm[["VDJ"]], color_by = "celltype",
                                  cols = vgm$GEX@misc$fctype_mod_cols,
                              color_lbl = "Cell type",
                              group_col = "clinical_condition")
filename <- paste0(plots_dir, "most_freq_CDR3s_aa.vdj.pdf")
ggsave(filename, tab_plt$plot, width = 10, height = 5)
tab_plt$plot
```

```{r most_freq_CDR3s_vj}
tab_plt <- most_freq_cd3s_aa_plot(vgm_HL[["VDJ"]], color_by = "celltype",
                                  cols = vgm$GEX@misc$fctype_mod_cols,
                              color_lbl = "Cell type",
                              group_col = "clinical_condition",
                              use.VJ = TRUE)
filename <- paste0(plots_dir, "most_freq_CDR3s_aa.vj.pdf")
ggsave(filename, tab_plt$plot, width = 10, height = 5)
```

# Session info

```{r}
sessionInfo()
```
