---
title: "InDen B cells | Pseudobulk DESeq2 analysis"
author: "Giorgio Gonnella"
date: 2024-06-13
output:
  html_document:
    theme: sandstone
params:
  prjpath: "/srv/baia/inden/"
  libpath: "/home/giorgio/R-pkg-Seurat5/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F, warning=F, echo=T)
.libPaths(c(params$libpath, .libPaths()))

library(Seurat)
library(dplyr)

analysis_root <- paste0(params$prjpath, "analysis-1/")

prev_step_dir <- paste0(analysis_root, "steps/105.0.P.B.split_plasmablasts/")
input_var_dir <- paste0(prev_step_dir, "results/vars/")
if (!dir.exists(input_var_dir)) {
  stop("Input variable directory does not exist: ", input_var_dir)
}

this_step_dir <- paste0(analysis_root, "steps/107.0.P.B.de_analysis/")
if (!dir.exists(this_step_dir)) {
  stop("Current step directory does not exist: ", this_step_dir)
}

var_dir <- paste0(this_step_dir, "results/vars/")
dir.create(var_dir, showWarnings = FALSE, recursive = TRUE)

helpers_dir <- paste0(params$prjpath, "helpers/")
source(paste0(helpers_dir, "de_helpers.R"))
```

```{r load_input_data}
so <- readRDS(file = paste0(input_var_dir, "splitted_so.rds"))
```

```{r prepare_results_slot}
so@misc$de <- list()
so@misc$de$all <- list()
so@misc$de$pval_filt <- list()
```

```{r select_genes}
so@misc$de$selgenes <- select_genes(so, verbose=T)
```

```{r prepare_pseudobulk_data}
clusters_col <- "pruned.labels_singleR_fine.mod"
pseudo <- AggregateExpression(so, assays = "RNA", return.seurat = TRUE,
                group.by = c("clinical_condition", "sample", clusters_col))
clusters_data <- pseudo@meta.data[[clusters_col]]
pseudo$cond.clusters <- paste0(pseudo$clinical_condition, "_", clusters_data)
Idents(pseudo) <- "cond.clusters"
cluster_names <- unique(clusters_data)
freqs = table(Idents(pseudo))
```

```{r run_de}
for (cluster in cluster_names) {
  ident.1 <- paste0("Subclinical_", cluster)
  ident.2 <- paste0("Hospitalized_", cluster)
  results <- run_pb_deseq2(pseudo, so@misc$de$selgenes, ident.1, ident.2, freqs)
  so@misc$de$all[[cluster]] <- results$all
  so@misc$de$pval_filt[[cluster]] <- results$pval_filt
}
```

```{r prepare_pseudobulk_data_unsplitted}
clusters_col2 = "pruned.labels_singleR_fine"
pseudo2 <- AggregateExpression(so, assays = "RNA", return.seurat = TRUE,
                 group.by = c("clinical_condition", "sample", clusters_col2))
clusters_data2 <- pseudo2@meta.data[[clusters_col2]]
pseudo2$cond.clusters <- paste0(pseudo2$clinical_condition, "_", clusters_data2)
Idents(pseudo2) <- "cond.clusters"
```

```{r run_de_unsplitted}
results2 <- run_pb_deseq2(pseudo2, so@misc$de$selgenes,
              "Subclinical_Plasmablasts", "Hospitalized_Plasmablasts")
so@misc$de$all[["Plasmablasts"]] <- results$all
so@misc$de$pval_filt[["Plasmablasts"]] <- results$pval_filt
```

```{r prepare_pseudobulk_data_total_cells}
pseudo3 <- AggregateExpression(so, assays = "RNA", return.seurat = TRUE,
                              group.by = c("clinical_condition", "sample"))
Idents(pseudo3) <- "clinical_condition"
```

```{r run_de_total_cells}
results3 <- run_pb_deseq2(pseudo3, so@misc$de$selgenes,
              "Subclinical", "Hospitalized")
so@misc$de$all[["Total"]] <- results$all
so@misc$de$pval_filt[["Total"]] <- results$pval_filt
```

```{r save_results}
saveRDS(so, paste0(var_dir, "so_w_deseq.rds"))
```

# Session info

```{r}
sessionInfo()
```

